import { QuizQuestion } from "@/lib/curriculum";

export const bimQuizzes: Record<number, QuizQuestion[]> = {
  1: [
    {
      id: "m1-q1",
      question: "¿Qué significa el acrónimo BIM en el contexto del diseño arquitectónico?",
      options: [
        { label: "A", text: "Building Information Modeling" },
        { label: "B", text: "Basic Integrated Modeling" },
        { label: "C", text: "Building Interface Management" },
        { label: "D", text: "Blueprint Information Method" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m1-q2",
      question: "¿Cuál es la principal diferencia entre BIM y CAD tradicional?",
      options: [
        { label: "A", text: "CAD es más moderno que BIM" },
        { label: "B", text: "BIM solo sirve para dibujos en 2D" },
        { label: "C", text: "BIM incorpora información inteligente y datos asociados a los elementos, no solo geometría" },
        { label: "D", text: "No existe diferencia significativa entre ambos" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m1-q3",
      question: "¿Qué estándar internacional regula la gestión de la información en proyectos BIM?",
      options: [
        { label: "A", text: "ISO 9001" },
        { label: "B", text: "ISO 19650" },
        { label: "C", text: "ISO 14001" },
        { label: "D", text: "ISO 27001" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m1-q4",
      question: "¿Qué nivel de madurez BIM se caracteriza por la colaboración plena entre disciplinas mediante un modelo compartido?",
      options: [
        { label: "A", text: "Level 0" },
        { label: "B", text: "Level 1" },
        { label: "C", text: "Level 2" },
        { label: "D", text: "Level 3" },
      ],
      correctAnswer: "D",
    },
    {
      id: "m1-q5",
      question: "¿Qué significa COBie en el contexto de los estándares BIM?",
      options: [
        { label: "A", text: "Computer Oriented Building Integration Engine" },
        { label: "B", text: "Construction Operations Building Information Exchange" },
        { label: "C", text: "Collaborative Object-Based Information Exchange" },
        { label: "D", text: "Centralized Operations for Building Infrastructure" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m1-q6",
      question: "¿En qué década comenzó a gestarse el concepto de BIM como lo conocemos hoy?",
      options: [
        { label: "A", text: "Años 1990" },
        { label: "B", text: "Años 2000" },
        { label: "C", text: "Años 2010" },
        { label: "D", text: "Años 1970" },
      ],
      correctAnswer: "D",
    },
    {
      id: "m1-q7",
      question: "¿Cuál es una ventaja competitiva clave del BIM sobre el CAD tradicional?",
      options: [
        { label: "A", text: "BIM permite la coordinación multidisciplinaria y detección de colisiones antes de la construcción" },
        { label: "B", text: "BIM permite crear dibujos más rápidos sin datos asociados" },
        { label: "C", text: "CAD permite mejor visualización 3D que BIM" },
        { label: "D", text: "BIM elimina completamente la necesidad de planos 2D" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m1-q8",
      question: "¿Qué describe el Level 2 de madurez BIM?",
      options: [
        { label: "A", text: "Trabajo en papel sin herramientas digitales" },
        { label: "B", text: "Modelos 3D colaborativos con intercambio de archivos mediante estándares abiertos como IFC" },
        { label: "C", text: "Un único modelo integrado compartido por todos en tiempo real" },
        { label: "D", text: "Solo modelado 2D con gestión electrónica de documentos" },
      ],
      correctAnswer: "B",
    },
  ],
  2: [
    {
      id: "m2-q1",
      question: "¿Cuál es la unidad de medida predeterminada en Revit para proyectos métricos?",
      options: [
        { label: "A", text: "Pulgadas" },
        { label: "B", text: "Centímetros" },
        { label: "C", text: "Milímetros" },
        { label: "D", text: "Metros" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m2-q2",
      question: "¿Qué elemento en Revit se comporta como un objeto basado en un sketch para definir su forma?",
      options: [
        { label: "A", text: "Muros" },
        { label: "B", text: "Pisos y techos" },
        { label: "C", text: "Puertas" },
        { label: "D", text: "Ventanas" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m2-q3",
      question: "¿Cómo se insertan puertas y ventanas en un modelo de Revit?",
      options: [
        { label: "A", text: "Se colocan como componentes que se alojan automáticamente en muros" },
        { label: "B", text: "Se modelan manualmente como geometría libre" },
        { label: "C", text: "Se importan desde AutoCAD únicamente" },
        { label: "D", text: "Se crean como familias in-place independientes" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m2-q4",
      question: "¿Qué tipo de vista en Revit permite ver el corte horizontal de un edificio a una altura determinada?",
      options: [
        { label: "A", text: "Vista de fachada" },
        { label: "B", text: "Vista 3D" },
        { label: "C", text: "Vista de renders" },
        { label: "D", text: "Planta de planta (Floor Plan)" },
      ],
      correctAnswer: "D",
    },
    {
      id: "m2-q5",
      question: "¿Qué herramienta de Revit se usa para agregar cotas (dimensiones) a los elementos del modelo?",
      options: [
        { label: "A", text: "La herramienta Cota (Dimension)" },
        { label: "B", text: "La herramienta Texto" },
        { label: "C", text: "La herramienta Etiqueta de sala" },
        { label: "D", text: "La herramienta Línea de detalle" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m2-q6",
      question: "¿Qué son las anotaciones en Revit?",
      options: [
        { label: "A", text: "Elementos 3D del modelo estructural" },
        { label: "B", text: "Textos, cotas, etiquetas y símbolos que aportan información al proyecto y son dependientes de la vista" },
        { label: "C", text: "Configuraciones de renderizado" },
        { label: "D", text: "Materiales asignados a los muros" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m2-q7",
      question: "¿Qué ocurre con una puerta en Revit si se elimina el muro donde está alojada?",
      options: [
        { label: "A", text: "La puerta permanece flotando en el espacio" },
        { label: "B", text: "La puerta se convierte en un elemento independiente" },
        { label: "C", text: "La puerta se elimina automáticamente junto con el muro" },
        { label: "D", text: "Revit impide eliminar el muro si tiene componentes alojados" },
      ],
      correctAnswer: "C",
    },
  ],
  3: [
    {
      id: "m3-q1",
      question: "¿Qué tipo de familia en Revit permite crear elementos personalizados con parámetros variables?",
      options: [
        { label: "A", text: "Familias paramétricas (componente)" },
        { label: "B", text: "Familias del sistema" },
        { label: "C", text: "Familias in-place sin parámetros" },
        { label: "D", text: "Grupos de modelo" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m3-q2",
      question: "¿Qué herramienta de Revit se utiliza para crear cubiertas con pendientes complejas?",
      options: [
        { label: "A", text: "La herramienta Muro" },
        { label: "B", text: "La herramienta Piso" },
        { label: "C", text: "La herramienta Cubierta (Roof) con definición por sketch y líneas de pendiente" },
        { label: "D", text: "No es posible crear cubiertas con pendiente en Revit" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m3-q3",
      question: "¿Qué son las familias anidadas en Revit?",
      options: [
        { label: "A", text: "Familias que no se pueden editar" },
        { label: "B", text: "Familias que se insertan dentro de otra familia para crear composiciones complejas" },
        { label: "C", text: "Familias que solo existen en el modelo, no en la biblioteca" },
        { label: "D", text: "Familias creadas automáticamente por Revit" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m3-q4",
      question: "¿Cómo se modela una escalera en Revit?",
      options: [
        { label: "A", text: "Solo se pueden importar escaleras desde AutoCAD" },
        { label: "B", text: "Modelando cada peldaño individualmente como muros" },
        { label: "C", text: "No es posible modelar escaleras en Revit" },
        { label: "D", text: "Usando la herramienta Escalera, que permite definirla por sketch o por componente con parámetros" },
      ],
      correctAnswer: "D",
    },
    {
      id: "m3-q5",
      question: "¿Qué es una familia compartida en Revit?",
      options: [
        { label: "A", text: "Una familia que solo puede usarse en un proyecto" },
        { label: "B", text: "Una familia que puede ser utilizada y categorizada en múltiples categorías del modelo" },
        { label: "C", text: "Una familia que se comparte entre usuarios por correo electrónico" },
        { label: "D", text: "Una familia que no tiene parámetros" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m3-q6",
      question: "¿Qué es una claraboya (skylight) en el contexto del modelado BIM?",
      options: [
        { label: "A", text: "Un tipo de muro cortina" },
        { label: "B", text: "Una abertura en la cubierta que permite la entrada de luz natural" },
        { label: "C", text: "Un tipo de ventana para muros" },
        { label: "D", text: "Un componente eléctrico del modelo" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m3-q7",
      question: "¿Cuál es la ventaja de usar familias paramétricas sobre familias in-place?",
      options: [
        { label: "A", text: "Las familias in-place son siempre más ligeras" },
        { label: "B", text: "Las familias paramétricas son reutilizables en múltiples proyectos y se pueden ajustar mediante parámetros sin recrearlas" },
        { label: "C", text: "No hay diferencia entre ambas" },
        { label: "D", text: "Las familias in-place permiten mejor renderizado" },
      ],
      correctAnswer: "B",
    },
  ],
  4: [
    {
      id: "m4-q1",
      question: "¿Qué formato de archivo abierto permite la interoperabilidad entre diferentes software BIM?",
      options: [
        { label: "A", text: "DWG" },
        { label: "B", text: "IFC (Industry Foundation Classes)" },
        { label: "C", text: "PDF" },
        { label: "D", text: "SKP" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m4-q2",
      question: "¿Qué es el Clash Detection en el contexto BIM?",
      options: [
        { label: "A", text: "Un método de renderizado fotorrealista" },
        { label: "B", text: "Un tipo de animación de recorrido" },
        { label: "C", text: "El proceso de detectar interferencias geométricas entre modelos de diferentes disciplinas" },
        { label: "D", text: "La creación de planos de construcción" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m4-q3",
      question: "¿Cómo se vinculan modelos de diferentes disciplinas en Revit?",
      options: [
        { label: "A", text: "Usando la función de Vínculo de Revit (Link Revit) para referenciar modelos externos sin modificarlos" },
        { label: "B", text: "Solo se pueden copiar y pegar elementos entre proyectos" },
        { label: "C", text: "No es posible vincular modelos de otras disciplinas" },
        { label: "D", text: "Importando todo como un bloque de AutoCAD" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m4-q4",
      question: "¿Qué software se utiliza comúnmente para la coordinación y detección de colisiones entre modelos BIM?",
      options: [
        { label: "A", text: "Microsoft Word" },
        { label: "B", text: "Autodesk Navisworks" },
        { label: "C", text: "Adobe Photoshop" },
        { label: "D", text: "Google SketchUp" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m4-q5",
      question: "¿Qué son los entregables BIM por fase?",
      options: [
        { label: "A", text: "Los pagos que se realizan en cada fase del proyecto" },
        { label: "B", text: "Las reuniones de coordinación entre equipos" },
        { label: "C", text: "Los permisos de construcción otorgados por el municipio" },
        { label: "D", text: "Los modelos y documentos que deben producirse en cada etapa del ciclo de vida del proyecto según el plan BIM" },
      ],
      correctAnswer: "D",
    },
    {
      id: "m4-q6",
      question: "¿Por qué es importante el formato IFC en proyectos BIM multidisciplinarios?",
      options: [
        { label: "A", text: "Porque permite intercambiar datos entre diferentes plataformas BIM sin depender de un software específico" },
        { label: "B", text: "Porque es un formato propietario de Autodesk" },
        { label: "C", text: "Porque solo funciona con Revit" },
        { label: "D", text: "Porque reduce el tamaño de los archivos" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m4-q7",
      question: "¿Cuál es la diferencia entre vincular (Link) e importar (Import) un modelo en Revit?",
      options: [
        { label: "A", text: "Vincular mantiene la referencia al archivo original y se actualiza con los cambios; importar incrusta los datos sin vínculo" },
        { label: "B", text: "No hay diferencia entre ambas opciones" },
        { label: "C", text: "Importar mantiene la referencia y vincular la pierde" },
        { label: "D", text: "Solo se puede importar, no vincular" },
      ],
      correctAnswer: "A",
    },
  ],
  5: [
    {
      id: "m5-q1",
      question: "¿Qué tipo de render se puede generar directamente desde Revit para visualizar el proyecto?",
      options: [
        { label: "A", text: "Solo renders en blanco y negro" },
        { label: "B", text: "Renders fotorrealistas utilizando el motor de renderizado integrado o vinculando con herramientas como Enscape o V-Ray" },
        { label: "C", text: "Solo vistas en alambre" },
        { label: "D", text: "Revit no tiene capacidad de renderizado" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m5-q2",
      question: "¿Qué son las planillas de cuantificación en el contexto BIM?",
      options: [
        { label: "A", text: "Planos de ubicación del proyecto" },
        { label: "B", text: "Programas de obra" },
        { label: "C", text: "Listas de materiales y cantidades extraídas automáticamente del modelo" },
        { label: "D", text: "Listas de revisiones del modelo" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m5-q3",
      question: "¿Qué permite la vista 360° en un proyecto BIM?",
      options: [
        { label: "A", text: "Realizar un recorrido virtual inmersivo que permite observar el espacio en todas las direcciones" },
        { label: "B", text: "Solo ver el modelo desde arriba" },
        { label: "C", text: "Exportar el modelo a formato DWG" },
        { label: "D", text: "Generar cortes del modelo automáticamente" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m5-q4",
      question: "¿Cómo se generan los presupuestos a partir de un modelo BIM?",
      options: [
        { label: "A", text: "Se calculan manualmente sin usar el modelo" },
        { label: "B", text: "Se extraen cantidades del modelo mediante planillas de cuantificación y se asocian a precios unitarios" },
        { label: "C", text: "Revit genera presupuestos automáticamente sin intervención" },
        { label: "D", text: "Solo se pueden calcular presupuestos en Excel" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m5-q5",
      question: "¿Qué formatos de exportación se utilizan comúnmente para publicar modelos BIM?",
      options: [
        { label: "A", text: "Solo formatos de imagen (JPG, PNG)" },
        { label: "B", text: "Solo formato RVT" },
        { label: "C", text: "IFC para interoperabilidad, DWG para planos, NWD/NWC para coordinación, y formatos de imagen para presentación" },
        { label: "D", text: "Solo formato PDF" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m5-q6",
      question: "¿Cuál es la ventaja de generar renders directamente desde el modelo BIM frente a usar un software externo?",
      options: [
        { label: "A", text: "El render se genera a partir del modelo actualizado sin necesidad de exportar e importar, evitando inconsistencias" },
        { label: "B", text: "No hay ventaja, siempre es mejor usar software externo" },
        { label: "C", text: "Los renders desde BIM son siempre de menor calidad" },
        { label: "D", text: "Solo ahorra tiempo de configuración de cámara" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m5-q7",
      question: "¿Qué son los recorridos virtuales en un proyecto BIM?",
      options: [
        { label: "A", text: "Revisiones del modelo entre equipos" },
        { label: "B", text: "Visitas físicas a la obra" },
        { label: "C", text: "Exportaciones del modelo en 2D" },
        { label: "D", text: "Animaciones que simulan caminar por el interior y exterior del edificio para evaluar espacialidad y diseño" },
      ],
      correctAnswer: "D",
    },
  ],
  6: [
    {
      id: "m6-q1",
      question: "¿Qué es el BIM 4D en el contexto de dimensiones BIM?",
      options: [
        { label: "A", text: "La dimensión de tiempo y planificación de la secuencia constructiva" },
        { label: "B", text: "La dimensión de costos" },
        { label: "C", text: "La dimensión de sostenibilidad" },
        { label: "D", text: "La dimensión de gestión de facilidades" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m6-q2",
      question: "¿Qué representa el BIM 5D?",
      options: [
        { label: "A", text: "La dimensión de sostenibilidad energética" },
        { label: "B", text: "La dimensión de costos y presupuestos integrados al modelo" },
        { label: "C", text: "La dimensión de tiempo" },
        { label: "D", text: "La dimensión de gestión de mantenimiento" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m6-q3",
      question: "¿Qué es un Digital Twin en el contexto de la construcción?",
      options: [
        { label: "A", text: "Una réplica física del edificio a escala" },
        { label: "B", text: "Un segundo modelo BIM idéntico al original" },
        { label: "C", text: "Una representación digital virtual del edificio que se actualiza en tiempo real con datos del edificio real" },
        { label: "D", text: "Un backup del proyecto en la nube" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m6-q4",
      question: "¿Qué aborda el BIM 7D?",
      options: [
        { label: "A", text: "La planificación temporal" },
        { label: "B", text: "El análisis de costos" },
        { label: "C", text: "La gestión de facilidades y mantenimiento del edificio durante su vida útil" },
        { label: "D", text: "El diseño arquitectónico conceptual" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m6-q5",
      question: "¿Cómo está impactando la Inteligencia Artificial en el BIM?",
      options: [
        { label: "A", text: "La IA no tiene relación con BIM" },
        { label: "B", text: "Solo sirve para generar imágenes" },
        { label: "C", text: "Automatiza tareas como detección de colisiones, optimización de diseños, estimación de costos y generación de modelos" },
        { label: "D", text: "Reemplaza completamente la necesidad de modelos BIM" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m6-q6",
      question: "¿Qué es la construcción automatizada y su relación con BIM?",
      options: [
        { label: "A", text: "Es la construcción sin ningún tipo de planificación" },
        { label: "B", text: "Es la automatización de los dibujos en 2D" },
        { label: "C", text: "Es lo mismo que la prefabricación tradicional" },
        { label: "D", text: "Es el uso de robots y maquinaria automatizada guiada por datos del modelo BIM para ejecutar tareas de construcción" },
      ],
      correctAnswer: "D",
    },
    {
      id: "m6-q7",
      question: "¿Qué aborda el BIM 6D?",
      options: [
        { label: "A", text: "La seguridad en obra" },
        { label: "B", text: "El análisis de sostenibilidad y eficiencia energética del edificio" },
        { label: "C", text: "La gestión de costos" },
        { label: "D", text: "La planificación del cronograma" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m6-q8",
      question: "¿Cuál es la ventaja de integrar BIM 4D con BIM 5D en un proyecto?",
      options: [
        { label: "A", text: "No se pueden integrar, son independientes" },
        { label: "B", text: "Solo mejora la visualización del modelo" },
        { label: "C", text: "Permite vincular el cronograma de obra con los costos, facilitando el control financiero en cada fase constructiva" },
        { label: "D", text: "Reduce el tamaño del archivo BIM" },
      ],
      correctAnswer: "C",
    },
  ],
};
