import { QuizQuestion } from "@/lib/curriculum";

export const cybersecurityQuizzes: Record<number, QuizQuestion[]> = {
  1: [
    {
      id: "m1-q1",
      question: "¿Qué representa la tríada CIA en ciberseguridad?",
      options: [
        { label: "A", text: "Central Intelligence Agency" },
        { label: "B", text: "Cifrado, Inspección y Autenticación" },
        { label: "C", text: "Confidencialidad, Integridad y Disponibilidad" },
        { label: "D", text: "Control, Identidad y Acceso" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m1-q2",
      question: "¿Qué tipo de malware cifra los archivos del usuario y exige un pago para restaurarlos?",
      options: [
        { label: "A", text: "Ransomware" },
        { label: "B", text: "Adware" },
        { label: "C", text: "Spyware" },
        { label: "D", text: "Rootkit" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m1-q3",
      question: "¿Cuál de los siguientes es un vector de ataque basado en la ingeniería social?",
      options: [
        { label: "A", text: "Ataque de fuerza bruta" },
        { label: "B", text: "Phishing" },
        { label: "C", text: "SQL Injection" },
        { label: "D", text: "Buffer Overflow" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m1-q4",
      question: "¿Qué principio de seguridad garantiza que la información no ha sido modificada de forma no autorizada?",
      options: [
        { label: "A", text: "Confidencialidad" },
        { label: "B", text: "Disponibilidad" },
        { label: "C", text: "Autenticidad" },
        { label: "D", text: "Integridad" },
      ],
      correctAnswer: "D",
    },
    {
      id: "m1-q5",
      question: "¿Qué es la gestión de riesgos en ciberseguridad?",
      options: [
        { label: "A", text: "El proceso de identificar, evaluar y priorizar riesgos para aplicar medidas de mitigación adecuadas" },
        { label: "B", text: "Eliminar todos los riesgos existentes" },
        { label: "C", text: "Contratar seguros contra ataques cibernéticos" },
        { label: "D", text: "Instalar únicamente antivirus" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m1-q6",
      question: "¿Cuál es la diferencia ética entre un hacker ético y un ciberdelincuente?",
      options: [
        { label: "A", text: "No hay diferencia en sus habilidades" },
        { label: "B", text: "El hacker ético solo prueba redes internas" },
        { label: "C", text: "El hacker ético cuenta con autorización para probar la seguridad; el ciberdelincuente actúa sin permiso y con fines maliciosos" },
        { label: "D", text: "El ciberdelincuente siempre trabaja para gobiernos" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m1-q7",
      question: "¿Qué es un modelo de amenazas (threat model)?",
      options: [
        { label: "A", text: "Un modelo matemático de criptografía" },
        { label: "B", text: "Un marco de análisis que identifica activos, amenazas, vulnerabilidades y contramedidas potenciales" },
        { label: "C", text: "Un software antivirus" },
        { label: "D", text: "Un tipo de malware" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m1-q8",
      question: "¿Qué tipo de malware se oculta dentro de un programa legítimo para engañar al usuario?",
      options: [
        { label: "A", text: "Gusano (Worm)" },
        { label: "B", text: "Troyano (Trojan)" },
        { label: "C", text: "Adware" },
        { label: "D", text: "Keylogger" },
      ],
      correctAnswer: "B",
    },
  ],
  2: [
    {
      id: "m2-q1",
      question: "¿Cuántas capas tiene el modelo OSI?",
      options: [
        { label: "A", text: "4 capas" },
        { label: "B", text: "5 capas" },
        { label: "C", text: "7 capas" },
        { label: "D", text: "10 capas" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m2-q2",
      question: "¿Qué es un firewall en la seguridad de redes?",
      options: [
        { label: "A", text: "Un dispositivo o software que filtra el tráfico de red según reglas de seguridad para bloquear accesos no autorizados" },
        { label: "B", text: "Un programa que acelera la red" },
        { label: "C", text: "Un tipo de cable de red" },
        { label: "D", text: "Un protocolo de encriptación" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m2-q3",
      question: "¿Cuál es la diferencia entre criptografía simétrica y asimétrica?",
      options: [
        { label: "A", text: "No hay diferencia" },
        { label: "B", text: "La simétrica usa la misma clave para cifrar y descifrar; la asimétrica usa un par de claves (pública y privada)" },
        { label: "C", text: "La asimétrica es más lenta y menos segura" },
        { label: "D", text: "La simétrica solo funciona en redes inalámbricas" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m2-q4",
      question: "¿Qué protocolo asegura la comunicación web mediante cifrado entre el navegador y el servidor?",
      options: [
        { label: "A", text: "HTTP" },
        { label: "B", text: "FTP" },
        { label: "C", text: "SMTP" },
        { label: "D", text: "TLS/SSL (HTTPS)" },
      ],
      correctAnswer: "D",
    },
    {
      id: "m2-q5",
      question: "¿Cuál es la función principal de un IDS (Intrusion Detection System)?",
      options: [
        { label: "A", text: "Bloquear ataques automáticamente" },
        { label: "B", text: "Detectar y alertar sobre actividades sospechosas o maliciosas en la red sin bloquearlas necesariamente" },
        { label: "C", text: "Cifrar el tráfico de red" },
        { label: "D", text: "Gestionar direcciones IP" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m2-q6",
      question: "¿Qué es una VPN y para qué se utiliza en ciberseguridad?",
      options: [
        { label: "A", text: "Un antivirus de red" },
        { label: "B", text: "Virtual Private Network, crea un túnel cifrado para proteger la comunicación a través de redes no confiables" },
        { label: "C", text: "Un tipo de firewall" },
        { label: "D", text: "Un protocolo de enrutamiento" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m2-q7",
      question: "¿Qué vulnerabilidad de seguridad es común en redes WiFi con cifrado WEP?",
      options: [
        { label: "A", text: "WEP es un cifrado imposible de romper" },
        { label: "B", text: "WEP tiene vulnerabilidades criptográficas conocidas que permiten descifrar el tráfico fácilmente" },
        { label: "C", text: "WEP ralentiza la conexión" },
        { label: "D", text: "WEP no permite conexiones simultáneas" },
      ],
      correctAnswer: "B",
    },
  ],
  3: [
    {
      id: "m3-q1",
      question: "¿Cuáles son las fases principales de una metodología de pentesting?",
      options: [
        { label: "A", text: "Reconocimiento, escaneo, explotación, post-explotación y reporte" },
        { label: "B", text: "Diseño, desarrollo, pruebas y despliegue" },
        { label: "C", text: "Planificación, presupuesto, ejecución y cierre" },
        { label: "D", text: "Instalación, configuración, uso y mantenimiento" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m3-q2",
      question: "¿Qué es OSINT en el contexto del ethical hacking?",
      options: [
        { label: "A", text: "Un tipo de malware" },
        { label: "B", text: "Open Source Intelligence, la recopilación de información pública sobre un objetivo sin interactuar directamente con él" },
        { label: "C", text: "Un framework de explotación" },
        { label: "D", text: "Un protocolo de red" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m3-q3",
      question: "¿Qué herramienta se utiliza principalmente para el escaneo de puertos y servicios en una red?",
      options: [
        { label: "A", text: "Metasploit" },
        { label: "B", text: "Nmap" },
        { label: "C", text: "Burp Suite" },
        { label: "D", text: "Wireshark" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m3-q4",
      question: "¿Qué es Metasploit Framework?",
      options: [
        { label: "A", text: "Una plataforma de penetración que proporciona herramientas para desarrollar y ejecutar exploits contra sistemas objetivo" },
        { label: "B", text: "Un editor de código" },
        { label: "C", text: "Un gestor de contraseñas" },
        { label: "D", text: "Un firewall de red" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m3-q5",
      question: "¿Cuál es la diferencia entre reconocimiento pasivo y activo?",
      options: [
        { label: "A", text: "No hay diferencia" },
        { label: "B", text: "El pasivo recopila información sin interactuar con el objetivo; el activo envía paquetes o solicitudes al objetivo para obtener datos" },
        { label: "C", text: "El activo es más seguro y silencioso" },
        { label: "D", text: "El pasivo solo funciona en redes internas" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m3-q6",
      question: "¿Qué es un escáner de vulnerabilidades como Nessus?",
      options: [
        { label: "A", text: "Un exploit automático" },
        { label: "B", text: "Un sniffer de paquetes" },
        { label: "C", text: "Una herramienta que identifica automáticamente vulnerabilidades conocidas en sistemas, aplicaciones y redes" },
        { label: "D", text: "Un generador de contraseñas" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m3-q7",
      question: "¿Qué fase del pentesting ocurre después de obtener acceso exitoso a un sistema?",
      options: [
        { label: "A", text: "Reconocimiento" },
        { label: "B", text: "Escaneo" },
        { label: "C", text: "Post-explotación, que incluye escalada de privilegios y recolección de datos" },
        { label: "D", text: "El pentesting termina al obtener acceso" },
      ],
      correctAnswer: "C",
    },
  ],
  4: [
    {
      id: "m4-q1",
      question: "¿Qué es el OWASP Top 10?",
      options: [
        { label: "A", text: "Un documento que lista las 10 vulnerabilidades de seguridad web más críticas" },
        { label: "B", text: "Una lista de los 10 mejores firewalls" },
        { label: "C", text: "Los 10 lenguajes de programación más seguros" },
        { label: "D", text: "Los 10 antivirus más utilizados" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m4-q2",
      question: "¿Qué tipo de ataque es SQL Injection?",
      options: [
        { label: "A", text: "Un ataque que inyecta código JavaScript en el navegador" },
        { label: "B", text: "Un ataque que inyecta código SQL malicioso a través de entradas del usuario para manipular la base de datos" },
        { label: "C", text: "Un ataque de fuerza bruta a contraseñas" },
        { label: "D", text: "Un ataque que roba cookies" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m4-q3",
      question: "¿Qué es el Cross-Site Scripting (XSS)?",
      options: [
        { label: "A", text: "Un método para compartir código entre sitios" },
        { label: "B", text: "Un ataque que inyecta scripts maliciosos en páginas web que otros usuarios visitan" },
        { label: "C", text: "Una técnica de optimización web" },
        { label: "D", text: "Un tipo de cifrado de datos" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m4-q4",
      question: "¿Cuál es la mitigación más efectiva contra SQL Injection?",
      options: [
        { label: "A", text: "Usar solo mayúsculas en las consultas" },
        { label: "B", text: "Ocultar los mensajes de error" },
        { label: "C", text: "Usar consultas parametrizadas (prepared statements)" },
        { label: "D", text: "Usar un firewall de aplicación web (WAF) como única defensa" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m4-q5",
      question: "¿Qué herramienta se utiliza como proxy interceptador para probar la seguridad de aplicaciones web?",
      options: [
        { label: "A", text: "Nmap" },
        { label: "B", text: "Burp Suite" },
        { label: "C", text: "Metasploit" },
        { label: "D", text: "Nessus" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m4-q6",
      question: "¿Cuál es la diferencia entre XSS reflejado y XSS almacenado?",
      options: [
        { label: "A", text: "No hay diferencia" },
        { label: "B", text: "El XSS reflejado se ejecuta desde una solicitud inmediata; el almacenado persiste en el servidor y afecta a múltiples usuarios" },
        { label: "C", text: "El reflejado es más peligroso que el almacenado" },
        { label: "D", text: "El almacenado solo afecta al usuario que lo inyecta" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m4-q7",
      question: "¿Qué es NoSQL Injection?",
      options: [
        { label: "A", text: "Un ataque a bases de datos relacionales" },
        { label: "B", text: "Una técnica de optimización de consultas" },
        { label: "C", text: "Un ataque que explota la falta de sanitización en entradas de bases de datos NoSQL como MongoDB" },
        { label: "D", text: "Un método para migrar datos entre bases de datos" },
      ],
      correctAnswer: "C",
    },
  ],
  5: [
    {
      id: "m5-q1",
      question: "¿Cuál es el principio de menor privilegio en seguridad en la nube?",
      options: [
        { label: "A", text: "Otorgar permisos de administrador a todos los usuarios" },
        { label: "B", text: "No otorgar permisos a nadie" },
        { label: "C", text: "Otorgar solo los permisos mínimos necesarios para que cada usuario o servicio realice sus funciones" },
        { label: "D", text: "Dar permisos máximos temporalmente y luego reducirlos" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m5-q2",
      question: "¿Qué es DevSecOps?",
      options: [
        { label: "A", text: "La integración de prácticas de seguridad en cada fase del ciclo de desarrollo de software (CI/CD pipeline)" },
        { label: "B", text: "Un tipo de firewall para la nube" },
        { label: "C", text: "Un lenguaje de programación seguro" },
        { label: "D", text: "Un framework de testing" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m5-q3",
      question: "¿Cuál es una consideración de seguridad importante al usar contenedores Docker?",
      options: [
        { label: "A", text: "Los contenedores son inherentemente seguros" },
        { label: "B", text: "Evitar ejecutar contenedores como root, usar imágenes base confiables y escanear vulnerabilidades en las imágenes" },
        { label: "C", text: "No es necesario actualizar las imágenes base" },
        { label: "D", text: "Docker elimina todas las vulnerabilidades automáticamente" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m5-q4",
      question: "¿Qué es la forense digital en ciberseguridad?",
      options: [
        { label: "A", text: "El diseño de sistemas seguros" },
        { label: "B", text: "El proceso de recopilar, preservar y analizar evidencia digital para investigar incidentes de seguridad" },
        { label: "C", text: "La creación de software antivirus" },
        { label: "D", text: "La monitorización de redes en tiempo real" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m5-q5",
      question: "¿Qué es un plan de respuesta a incidentes?",
      options: [
        { label: "A", text: "Un contrato con una empresa de seguridad" },
        { label: "B", text: "Un documento que describe los pasos a seguir cuando ocurre un incidente de seguridad para minimizar el impacto" },
        { label: "C", text: "Un software de detección de intrusos" },
        { label: "D", text: "Una lista de contraseñas de emergencia" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m5-q6",
      question: "¿Qué servicio de seguridad en la nube de AWS ayuda a evaluar la configuración de recursos?",
      options: [
        { label: "A", text: "AWS Config" },
        { label: "B", text: "AWS S3" },
        { label: "C", text: "AWS Lambda" },
        { label: "D", text: "AWS EC2" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m5-q7",
      question: "¿Por qué es importante la seguridad en el pipeline CI/CD?",
      options: [
        { label: "A", text: "No es relevante para la seguridad" },
        { label: "B", text: "Solo para cumplir con regulaciones" },
        { label: "C", text: "Porque un pipeline comprometido puede introducir código malicioso en producción, afectando a todos los usuarios" },
        { label: "D", text: "Porque ralentiza el desarrollo" },
      ],
      correctAnswer: "C",
    },
  ],
  6: [
    {
      id: "m6-q1",
      question: "¿Qué certificación de ciberseguridad es reconocida como fundamental para profesionales entry-level?",
      options: [
        { label: "A", text: "OSCP" },
        { label: "B", text: "CompTIA Security+" },
        { label: "C", text: "CISSP" },
        { label: "D", text: "CEH" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m6-q2",
      question: "¿Qué es un CTF en el contexto de ciberseguridad?",
      options: [
        { label: "A", text: "Capture The Flag, una competencia donde los participantes resuelven desafíos de seguridad para encontrar 'banderas' ocultas" },
        { label: "B", text: "Un tipo de certificación" },
        { label: "C", text: "Un framework de testing" },
        { label: "D", text: "Un tipo de malware" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m6-q3",
      question: "¿Qué certificación se enfoca específicamente en ethical hacking y técnicas de penetración?",
      options: [
        { label: "A", text: "CompTIA A+" },
        { label: "B", text: "CEH (Certified Ethical Hacker)" },
        { label: "C", text: "AWS Solutions Architect" },
        { label: "D", text: "PMP" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m6-q4",
      question: "¿Qué es un programa de bug bounty?",
      options: [
        { label: "A", text: "Un programa para encontrar errores en software de forma interna" },
        { label: "B", text: "Un concurso de programación" },
        { label: "C", text: "Un tipo de antivirus" },
        { label: "D", text: "Un programa donde organizaciones ofrecen recompensas económicas a investigadores que reporten vulnerabilidades de forma responsable" },
      ],
      correctAnswer: "D",
    },
    {
      id: "m6-q5",
      question: "¿Qué plataforma online es conocida por ofrecer máquinas virtuales vulnerables para practicar hacking ético?",
      options: [
        { label: "A", text: "GitHub" },
        { label: "B", text: "Stack Overflow" },
        { label: "C", text: "HackTheBox" },
        { label: "D", text: "LinkedIn Learning" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m6-q6",
      question: "¿Qué es el reporte responsable de vulnerabilidades?",
      options: [
        { label: "A", text: "Publicar la vulnerabilidad inmediatamente en redes sociales" },
        { label: "B", text: "Notificar privadamente al fabricante o affected party antes de cualquier divulgación pública, dando tiempo para remediar" },
        { label: "C", text: "Ignorar la vulnerabilidad si no te afecta directamente" },
        { label: "D", text: "Vender la vulnerabilidad al mejor postor" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m6-q7",
      question: "¿Cuál es la certificación OSCP y qué la diferencia de otras certificaciones?",
      options: [
        { label: "A", text: "Es una certificación teórica sobre políticas de seguridad" },
        { label: "B", text: "Offensive Security Certified Professional, es un examen práctico de 24 horas donde se debe comprometer múltiples máquinas" },
        { label: "C", text: "Es una certificación de gestión de proyectos" },
        { label: "D", text: "Solo requiere un examen de opción múltiple" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m6-q8",
      question: "¿Qué rol profesional se encarga de monitorizar y responder a incidentes de seguridad en tiempo real?",
      options: [
        { label: "A", text: "Arquitecto de seguridad" },
        { label: "B", text: "Auditor de cumplimiento" },
        { label: "C", text: "Analista SOC (Security Operations Center)" },
        { label: "D", text: "Ingeniero de datos" },
      ],
      correctAnswer: "C",
    },
  ],
};
