import { QuizQuestion } from "@/lib/curriculum";

export const iaQuizzes: Record<number, QuizQuestion[]> = {
  1: [
    {
      id: "m1-q1",
      question: "¿Cuál es la diferencia fundamental entre IA estrecha (Narrow AI) e IA general (AGI)?",
      options: [
        { label: "A", text: "La IA estrecha es más potente que la AGI" },
        { label: "B", text: "La IA estrecha está especializada en una tarea específica; la AGI sería capaz de aprender y razonar sobre cualquier dominio como un humano" },
        { label: "C", text: "La AGI ya existe y se usa en asistentes virtuales" },
        { label: "D", text: "No hay diferencia, son sinónimos" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m1-q2",
      question: "¿En qué evento se considera el nacimiento oficial de la Inteligencia Artificial como disciplina?",
      options: [
        { label: "A", text: "La publicación del Test de Turing en 1950" },
        { label: "B", text: "La Conferencia de Dartmouth en 1956" },
        { label: "C", text: "El lanzamiento de ChatGPT en 2022" },
        { label: "D", text: "La invención de la computadora ENIAC en 1945" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m1-q3",
      question: "¿Qué tipo de aprendizaje utiliza datos etiquetados para entrenar un modelo que prediga salidas a partir de entradas?",
      options: [
        { label: "A", text: "Aprendizaje no supervisado" },
        { label: "B", text: "Aprendizaje por refuerzo" },
        { label: "C", text: "Aprendizaje supervisado" },
        { label: "D", text: "Aprendizaje auto-supervisado" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m1-q4",
      question: "¿Qué biblioteca de Python se utiliza principalmente para la manipulación de datos tabulares con DataFrames?",
      options: [
        { label: "A", text: "NumPy" },
        { label: "B", text: "Matplotlib" },
        { label: "C", text: "TensorFlow" },
        { label: "D", text: "Pandas" },
      ],
      correctAnswer: "D",
    },
    {
      id: "m1-q5",
      question: "¿Qué fueron los 'inviernos de la IA'?",
      options: [
        { label: "A", text: "Períodos donde la IA funcionó mejor en climas fríos" },
        { label: "B", text: "Épocas de reducción drástica en financiamiento e interés causadas por expectativas no cumplidas" },
        { label: "C", text: "Nombre de proyectos secretos de IA militar" },
        { label: "D", text: "Períodos donde los algoritmos de IA se congelaban por errores de software" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m1-q6",
      question: "¿En qué paradigma de aprendizaje un agente aprende a tomar decisiones recibiendo recompensas o castigos de un entorno?",
      options: [
        { label: "A", text: "Aprendizaje supervisado" },
        { label: "B", text: "Aprendizaje no supervisado" },
        { label: "C", text: "Aprendizaje por refuerzo (Reinforcement Learning)" },
        { label: "D", text: "Aprendizaje transferido" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m1-q7",
      question: "¿Qué es el sesgo algorítmico en el contexto de la ética en IA?",
      options: [
        { label: "A", text: "Cuando un algoritmo favorece a la empresa que lo creó" },
        { label: "B", text: "Cuando los modelos aprenden y reproducen prejuicios sociales presentes en los datos de entrenamiento" },
        { label: "C", text: "Un error de programación en el código del modelo" },
        { label: "D", text: "La preferencia de un modelo por usar más memoria de la necesaria" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m1-q8",
      question: "¿Qué convergencia de factores impulsó el resurgimiento moderno del deep learning en la década de 2010?",
      options: [
        { label: "A", text: "Mejores lenguajes de programación y compiladores" },
        { label: "B", text: "Datos masivos, poder computacional (GPUs) y avances algorítmicos" },
        { label: "C", text: "Mayor financiamiento gubernamental exclusivamente" },
        { label: "D", text: "La invención del internet" },
      ],
      correctAnswer: "B",
    },
  ],
  2: [
    {
      id: "m2-q1",
      question: "¿Cuál es la estrategia más adecuada para manejar valores faltantes cuando estos no son aleatorios (MNAR)?",
      options: [
        { label: "A", text: "Eliminar siempre todas las filas con datos faltantes" },
        { label: "B", text: "Imputar siempre con la media sin considerar el mecanismo" },
        { label: "C", text: "Analizar el mecanismo de datos faltantes y usar imputación con modelos predictivos o indicadores de ausencia según el caso" },
        { label: "D", text: "Ignorar los datos faltantes, los algoritmos los manejan automáticamente" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m2-q2",
      question: "¿Cuál es la diferencia entre regresión lineal y regresión logística?",
      options: [
        { label: "A", text: "La regresión lineal predice valores continuos; la regresión logística predice probabilidades para clasificación binaria" },
        { label: "B", text: "Ambas son lo mismo, solo cambian los nombres" },
        { label: "C", text: "La regresión logística es más rápida que la lineal" },
        { label: "D", text: "La regresión lineal usa la función sigmoide" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m2-q3",
      question: "¿Qué problema principal de los árboles de decisión resuelve Random Forest?",
      options: [
        { label: "A", text: "La lentitud en la predicción" },
        { label: "B", text: "La incapacidad de manejar variables categóricas" },
        { label: "C", text: "El sobreajuste (overfitting) mediante el ensemble de múltiples árboles con aleatorización" },
        { label: "D", text: "La necesidad de normalizar los datos" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m2-q4",
      question: "¿Qué técnica de validación divide los datos en k partes, entrena k veces con k-1 partes y evalúa con la parte restante?",
      options: [
        { label: "A", text: "Hold-out validation" },
        { label: "B", text: "K-fold cross-validation" },
        { label: "C", text: "Leave-one-out cross-validation" },
        { label: "D", text: "Bootstrapping" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m2-q5",
      question: "¿Qué métrica de evaluación es más importante en un problema de detección de cáncer donde no se debe pasar por alto ningún caso positivo?",
      options: [
        { label: "A", text: "Accuracy" },
        { label: "B", text: "Precision" },
        { label: "C", text: "Recall (sensibilidad)" },
        { label: "D", text: "Specificity" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m2-q6",
      question: "¿Qué codificación de variables categóricas introduce un orden artificial que no existe en las categorías?",
      options: [
        { label: "A", text: "One-hot encoding" },
        { label: "B", text: "Target encoding" },
        { label: "C", text: "Label encoding" },
        { label: "D", text: "Frequency encoding" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m2-q7",
      question: "¿Qué ocurre cuando un modelo tiene underfitting (subajuste)?",
      options: [
        { label: "A", text: "El modelo memoriza los datos de entrenamiento incluyendo el ruido" },
        { label: "B", text: "El modelo es demasiado simple y no captura los patrones de los datos, rindiendo mal tanto en entrenamiento como en test" },
        { label: "C", text: "El modelo rinde perfectamente en test" },
        { label: "D", text: "El modelo necesita más epochs para mejorar" },
      ],
      correctAnswer: "B",
    },
  ],
  3: [
    {
      id: "m3-q1",
      question: "¿Qué función de activación es la más utilizada en redes neuronales modernas por su eficiencia y mitigación del desvanecimiento del gradiente?",
      options: [
        { label: "A", text: "Sigmoide" },
        { label: "B", text: "Tanh" },
        { label: "C", text: "ReLU (Rectified Linear Unit)" },
        { label: "D", text: "Step function" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m3-q2",
      question: "¿Qué operación fundamental de las CNN aplica filtros pequeños que se deslizan sobre la imagen para detectar patrones locales?",
      options: [
        { label: "A", text: "Pooling" },
        { label: "B", text: "Convolución" },
        { label: "C", text: "Dropout" },
        { label: "D", text: "Batch normalization" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m3-q3",
      question: "¿Qué problema de las RNN simples resuelven las LSTM?",
      options: [
        { label: "A", text: "La incapacidad de procesar secuencias largas" },
        { label: "B", text: "El desvanecimiento del gradiente (vanishing gradient) mediante puertas de memoria que mantienen información a largo plazo" },
        { label: "C", text: "La lentitud en el entrenamiento" },
        { label: "D", text: "La imposibilidad de usar GPU" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m3-q4",
      question: "¿Cuál es la innovación clave de la arquitectura Transformer frente a las RNN?",
      options: [
        { label: "A", text: "Usa menos parámetros que las RNN" },
        { label: "B", text: "El mecanismo de auto-atención que permite evaluar la importancia de cada elemento respecto a todos los demás sin limitación secuencial" },
        { label: "C", text: "No requiere datos de entrenamiento" },
        { label: "D", text: "Solo funciona para traducción automática" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m3-q5",
      question: "¿Qué componente de la LSTM decide qué información del estado anterior debe descartarse?",
      options: [
        { label: "A", text: "Puerta de entrada (input gate)" },
        { label: "B", text: "Puerta de salida (output gate)" },
        { label: "C", text: "Puerta de olvido (forget gate)" },
        { label: "D", text: "Celda de memoria" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m3-q6",
      question: "¿Qué arquitectura CNN introdujo las conexiones residuales (skip connections) para resolver el problema del degradamiento del gradiente en redes muy profundas?",
      options: [
        { label: "A", text: "AlexNet" },
        { label: "B", text: "VGGNet" },
        { label: "C", text: "ResNet" },
        { label: "D", text: "LeNet-5" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m3-q7",
      question: "En el mecanismo de auto-atención del Transformer, ¿qué representan los vectores Query (Q), Key (K) y Value (V)?",
      options: [
        { label: "A", text: "Q es la consulta, K es el contexto y V es la respuesta final" },
        { label: "B", text: "Q y K determinan la atención (similitud) entre tokens, y V proporciona la información a transmitir" },
        { label: "C", text: "Son tres capas diferentes de la red" },
        { label: "D", text: "Q es la entrada, K es el filtro y V es la salida de la convolución" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m3-q8",
      question: "¿Qué ventaja tienen las GRU sobre las LSTM?",
      options: [
        { label: "A", text: "Las GRU siempre obtienen mejor rendimiento" },
        { label: "B", text: "Las GRU tienen menos parámetros al combinar puertas, lo que permite entrenamiento más rápido con resultados comparables" },
        { label: "C", text: "Las GRU no necesitan datos secuenciales" },
        { label: "D", text: "Las GRU solo funcionan para clasificación de imágenes" },
      ],
      correctAnswer: "B",
    },
  ],
  4: [
    {
      id: "m4-q1",
      question: "¿Qué tarea de entrenamiento utilizan los modelos de lenguaje grandes (LLMs) como GPT para aprender las estadísticas del lenguaje?",
      options: [
        { label: "A", text: "Clasificación de sentimientos" },
        { label: "B", text: "Predicción del siguiente token (token prediction)" },
        { label: "C", text: "Detección de objetos" },
        { label: "D", text: "Segmentación semántica" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m4-q2",
      question: "¿Qué técnica de prompting consiste en pedir al modelo que razone paso a paso para mejorar su rendimiento en problemas complejos?",
      options: [
        { label: "A", text: "Zero-shot prompting" },
        { label: "B", text: "Chain-of-Thought (CoT) prompting" },
        { label: "C", text: "Few-shot prompting" },
        { label: "D", text: "Adversarial prompting" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m4-q3",
      question: "¿Qué tecnología subyacente utilizan modelos de generación de imágenes como Stable Diffusion?",
      options: [
        { label: "A", text: "Redes neuronales convolucionales tradicionales" },
        { label: "B", text: "Modelos de difusión que aprenden a eliminar ruido progresivamente para generar imágenes" },
        { label: "C", text: "Redes generativas adversariales (GANs) exclusivamente" },
        { label: "D", text: "Autoencoders variacionales (VAEs) exclusivamente" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m4-q4",
      question: "¿Qué es RAG (Retrieval-Augmented Generation) en el contexto de los LLMs?",
      options: [
        { label: "A", text: "Un modelo de generación de imágenes" },
        { label: "B", text: "Una técnica que combina recuperación de información relevante con generación para que el modelo use conocimiento externo actualizado" },
        { label: "C", text: "Un método de compresión de modelos" },
        { label: "D", text: "Una forma de fine-tuning más rápida" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m4-q5",
      question: "¿Qué es RLHF en el entrenamiento de LLMs?",
      options: [
        { label: "A", text: "Reinforcement Learning from Human Feedback, una técnica para alinear el modelo con preferencias humanas" },
        { label: "B", text: "Un tipo de red neuronal recurrente" },
        { label: "C", text: "Un formato de archivo para modelos" },
        { label: "D", text: "Un benchmark de evaluación de modelos" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m4-q6",
      question: "¿Qué principio del prompt engineering consiste en proporcionar ejemplos del formato deseado en la instrucción?",
      options: [
        { label: "A", text: "Zero-shot prompting" },
        { label: "B", text: "Few-shot prompting (proporcionar ejemplos de entrada/salida)" },
        { label: "C", text: "Adversarial prompting" },
        { label: "D", text: "Prompt injection" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m4-q7",
      question: "¿Qué es el in-context learning en los LLMs?",
      options: [
        { label: "A", text: "Aprender de ejemplos proporcionados en el prompt sin cambiar los pesos del modelo" },
        { label: "B", text: "Entrenar el modelo con datos contextuales específicos" },
        { label: "C", text: "Un tipo de fine-tuning" },
        { label: "D", text: "Una técnica para reducir el tamaño del modelo" },
      ],
      correctAnswer: "A",
    },
  ],
  5: [
    {
      id: "m5-q1",
      question: "¿Qué arquitectura de red neuronal se utiliza comúnmente para la detección de objetos en tiempo real?",
      options: [
        { label: "A", text: "YOLO (You Only Look Once)" },
        { label: "B", text: "Autoencoder" },
        { label: "C", text: "LSTM" },
        { label: "D", text: "GAN" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m5-q2",
      question: "¿Qué tarea del NLP consiste en determinar la opinión o emoción expresada en un texto?",
      options: [
        { label: "A", text: "Reconocimiento de entidades nombradas (NER)" },
        { label: "B", text: "Análisis de sentimientos" },
        { label: "C", text: "Lematización" },
        { label: "D", text: "Etiquetado POS (Part-of-Speech)" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m5-q3",
      question: "¿Qué técnica utilizan los sistemas de recomendación para sugerir items basándose en las preferencias de usuarios similares?",
      options: [
        { label: "A", text: "Filtrado basado en contenido" },
        { label: "B", text: "Filtrado colaborativo" },
        { label: "C", text: "Búsqueda por palabras clave" },
        { label: "D", text: "Ordenamiento aleatorio" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m5-q4",
      question: "¿Cuál de los siguientes es un servicio de IA en la nube de Amazon Web Services?",
      options: [
        { label: "A", text: "Azure Cognitive Services" },
        { label: "B", text: "Google Vertex AI" },
        { label: "C", text: "AWS SageMaker" },
        { label: "D", text: "IBM Watson Studio" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m5-q5",
      question: "¿Qué es la segmentación semántica en visión por computadora?",
      options: [
        { label: "A", text: "Clasificar una imagen completa en una categoría" },
        { label: "B", text: "Asignar una clase a cada píxel de la imagen para identificar las regiones y sus categorías" },
        { label: "C", text: "Detectar bordes en una imagen" },
        { label: "D", text: "Comprimir una imagen manteniendo su calidad" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m5-q6",
      question: "¿Qué modelo de NLP basado en Transformers se entrena enmascarando palabras para aprender representaciones bidireccionales del lenguaje?",
      options: [
        { label: "A", text: "GPT" },
        { label: "B", text: "BERT" },
        { label: "C", text: "YOLO" },
        { label: "D", text: "ResNet" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m5-q7",
      question: "¿Cuál es una ventaja de usar servicios de IA en la nube frente a implementar modelos localmente?",
      options: [
        { label: "A", text: "Los modelos en la nube siempre son más precisos" },
        { label: "B", text: "No se necesita conexión a internet" },
        { label: "C", text: "Escalabilidad, infraestructura gestionada y acceso a modelos pre-entrenados sin necesidad de hardware especializado" },
        { label: "D", text: "Los datos siempre son más seguros en la nube" },
      ],
      correctAnswer: "C",
    },
  ],
  6: [
    {
      id: "m6-q1",
      question: "¿Cuál es la fase más laboriosa de un proyecto de Machine Learning según la regla empírica de la industria?",
      options: [
        { label: "A", text: "El entrenamiento del modelo" },
        { label: "B", text: "La preparación y limpieza de datos (aproximadamente el 80% del tiempo)" },
        { label: "C", text: "El despliegue del modelo" },
        { label: "D", text: "La documentación del proyecto" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m6-q2",
      question: "¿Qué es MLOps y por qué es importante?",
      options: [
        { label: "A", text: "Un lenguaje de programación para IA" },
        { label: "B", text: "Un framework de deep learning" },
        { label: "C", text: "El conjunto de prácticas que automatizan y gestionan el ciclo de vida de los modelos de ML en producción, asegurando su fiabilidad y escalabilidad" },
        { label: "D", text: "Una certificación de Python" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m6-q3",
      question: "¿Qué certificación de IA de Google es reconocida para demostrar competencia en Machine Learning y Cloud AI?",
      options: [
        { label: "A", text: "CompTIA Security+" },
        { label: "B", text: "Google Professional Machine Learning Engineer" },
        { label: "C", text: "AWS Solutions Architect" },
        { label: "D", text: "PMP (Project Management Professional)" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m6-q4",
      question: "¿Qué es la IA multimodal?",
      options: [
        { label: "A", text: "Una IA que solo procesa texto" },
        { label: "B", text: "Una IA que puede procesar y relacionar múltiples tipos de datos simultáneamente (texto, imagen, audio, video)" },
        { label: "C", text: "Un modelo que cambia de modo entre entrenamiento e inferencia" },
        { label: "D", text: "Una técnica de compresión de modelos" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m6-q5",
      question: "¿Qué es un Digital Twin en el contexto de la IA?",
      options: [
        { label: "A", text: "Una copia de seguridad de un modelo de IA" },
        { label: "B", text: "Una réplica digital de un sistema físico que se actualiza con datos en tiempo real para simulación y análisis" },
        { label: "C", text: "Un clon de un modelo de lenguaje" },
        { label: "D", text: "Un algoritmo de duplicación de datos" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m6-q6",
      question: "¿Qué problema aborda el concepto de 'data drift' en MLOps?",
      options: [
        { label: "A", text: "La pérdida de datos durante la transmisión" },
        { label: "B", text: "El cambio en la distribución de los datos de entrada con respecto a los datos de entrenamiento, que degrada el rendimiento del modelo en producción" },
        { label: "C", text: "La fuga de datos entre conjuntos de entrenamiento y test" },
        { label: "D", text: "El desplazamiento de datos entre servidores" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m6-q7",
      question: "¿Cuál es el orden correcto de las fases de un pipeline de proyecto de Machine Learning?",
      options: [
        { label: "A", text: "Despliegue → Entrenamiento → Recolección de datos → Evaluación" },
        { label: "B", text: "Recolección y preparación de datos → Entrenamiento del modelo → Evaluación y ajuste → Despliegue y monitorización" },
        { label: "C", text: "Entrenamiento → Recolección de datos → Evaluación → Despliegue" },
        { label: "D", text: "Evaluación → Preparación → Entrenamiento → Despliegue" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m6-q8",
      question: "¿Qué es AGI (Artificial General Intelligence)?",
      options: [
        { label: "A", text: "Un modelo de lenguaje de OpenAI" },
        { label: "B", text: "Una IA capaz de aprender y razonar sobre cualquier dominio intelectual al nivel humano, actualmente un objetivo teórico" },
        { label: "C", text: "La versión premium de ChatGPT" },
        { label: "D", text: "Un tipo de red neuronal convolucional" },
      ],
      correctAnswer: "B",
    },
  ],
};
