import { QuizQuestion } from "@/lib/curriculum";

export const webDevQuizzes: Record<number, QuizQuestion[]> = {
  1: [
    {
      id: "m1-q1",
      question: "¿Cuál es la estructura básica correcta de un documento HTML5?",
      options: [
        { label: "A", text: "<html><head></head><body></body></html>" },
        { label: "B", text: "<!DOCTYPE html><html><head></head><body></body></html>" },
        { label: "C", text: "<document><header></header><main></main></document>" },
        { label: "D", text: "<html5><head></head><body></body></html5>" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m1-q2",
      question: "¿Qué etiqueta semántica de HTML5 se utiliza para definir el contenido principal de una página?",
      options: [
        { label: "A", text: "<main>" },
        { label: "B", text: "<div>" },
        { label: "C", text: "<section>" },
        { label: "D", text: "<content>" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m1-q3",
      question: "¿Cuál es la diferencia clave entre desarrollo web frontend y backend?",
      options: [
        { label: "A", text: "El frontend se ejecuta en el servidor, el backend en el navegador" },
        { label: "B", text: "No hay diferencia, son lo mismo" },
        { label: "C", text: "El frontend se ejecuta en el navegador del usuario; el backend se ejecuta en el servidor" },
        { label: "D", text: "El backend se encarga del diseño visual" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m1-q4",
      question: "¿Qué atributo de HTML5 permite validar que un campo contenga una dirección de correo electrónico válida?",
      options: [
        { label: "A", text: "type=\"text\"" },
        { label: "B", text: "validate=\"email\"" },
        { label: "C", text: "format=\"email\"" },
        { label: "D", text: "type=\"email\"" },
      ],
      correctAnswer: "D",
    },
    {
      id: "m1-q5",
      question: "¿Qué etiqueta se utiliza en HTML5 para insertar un video?",
      options: [
        { label: "A", text: "<media>" },
        { label: "B", text: "<movie>" },
        { label: "C", text: "<video>" },
        { label: "D", text: "<film>" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m1-q6",
      question: "¿Cuál es la función de la etiqueta <nav> en HTML5?",
      options: [
        { label: "A", text: "Crear un enlace externo" },
        { label: "B", text: "Definir la navegación principal del sitio" },
        { label: "C", text: "Insertar una barra de progreso" },
        { label: "D", text: "Definir un párrafo de texto" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m1-q7",
      question: "¿Qué atributo de HTML5 hace que un campo de formulario sea obligatorio antes de enviar?",
      options: [
        { label: "A", text: "mandatory=\"true\"" },
        { label: "B", text: "required" },
        { label: "C", text: "validate=\"required\"" },
        { label: "D", text: "notnull=\"true\"" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m1-q8",
      question: "¿Cuál de estas etiquetas es semántica en HTML5 y se usa para contenido complementario o sidebar?",
      options: [
        { label: "A", text: "<sidebar>" },
        { label: "B", text: "<aside>" },
        { label: "C", text: "<extra>" },
        { label: "D", text: "<div class='side'>" },
      ],
      correctAnswer: "B",
    },
  ],
  2: [
    {
      id: "m2-q1",
      question: "¿Qué propiedad CSS determina qué estilo se aplica cuando hay conflictos entre selectores?",
      options: [
        { label: "A", text: "La herencia" },
        { label: "B", text: "El orden alfabético" },
        { label: "C", text: "La especificidad (specificity)" },
        { label: "D", text: "La última declaración siempre gana" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m2-q2",
      question: "¿Qué modelo de layout CSS permite distribuir elementos en una sola dirección, fila o columna?",
      options: [
        { label: "A", text: "Flexbox" },
        { label: "B", text: "CSS Grid" },
        { label: "C", text: "Float" },
        { label: "D", text: "Position absolute" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m2-q3",
      question: "¿Qué propiedad de Flexbox define la dirección principal de los elementos hijos?",
      options: [
        { label: "A", text: "flex-wrap" },
        { label: "B", text: "flex-direction" },
        { label: "C", text: "justify-content" },
        { label: "D", text: "align-items" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m2-q4",
      question: "¿Qué enfoque de diseño responsivo consiste en diseñar primero para móviles y luego escalar hacia pantallas mayores?",
      options: [
        { label: "A", text: "Desktop First" },
        { label: "B", text: "Mobile First" },
        { label: "C", text: "Graceful Degradation" },
        { label: "D", text: "Fixed Layout" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m2-q5",
      question: "¿Cuál de los siguientes selectores CSS tiene mayor especificidad?",
      options: [
        { label: "A", text: ".clase" },
        { label: "B", text: "#id" },
        { label: "C", text: "elemento" },
        { label: "D", text: "*" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m2-q6",
      question: "¿Cómo se define una variable CSS personalizada?",
      options: [
        { label: "A", text: "$mi-variable: valor;" },
        { label: "B", text: "@mi-variable: valor;" },
        { label: "C", text: "--mi-variable: valor;" },
        { label: "D", text: "var mi-variable = valor;" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m2-q7",
      question: "¿Qué unidad CSS es relativa al ancho del viewport?",
      options: [
        { label: "A", text: "vw" },
        { label: "B", text: "px" },
        { label: "C", text: "em" },
        { label: "D", text: "pt" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m2-q8",
      question: "¿Qué propiedad de CSS Grid define el número y tamaño de las columnas?",
      options: [
        { label: "A", text: "grid-rows" },
        { label: "B", text: "grid-template-columns" },
        { label: "C", text: "grid-gap" },
        { label: "D", text: "grid-flow" },
      ],
      correctAnswer: "B",
    },
  ],
  3: [
    {
      id: "m3-q1",
      question: "¿Qué palabra clave de ES6+ declara una variable que no puede ser reasignada después de su inicialización?",
      options: [
        { label: "A", text: "var" },
        { label: "B", text: "const" },
        { label: "C", text: "let" },
        { label: "D", text: "static" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m3-q2",
      question: "¿Qué es un closure en JavaScript?",
      options: [
        { label: "A", text: "Un tipo de bucle optimizado" },
        { label: "B", text: "Un método para cerrar conexiones de red" },
        { label: "C", text: "Una función que recuerda el ámbito léxico en el que fue creada, incluso cuando se ejecuta fuera de ese ámbito" },
        { label: "D", text: "Una forma de declarar variables globales" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m3-q3",
      question: "¿Cuál es la diferencia principal entre una arrow function y una function tradicional?",
      options: [
        { label: "A", text: "Las arrow functions no tienen su propio 'this', lo heredan del contexto donde se definen" },
        { label: "B", text: "Las arrow functions no pueden recibir parámetros" },
        { label: "C", text: "Las arrow functions son más lentas" },
        { label: "D", text: "No hay diferencia funcional entre ambas" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m3-q4",
      question: "¿Qué método de los arrays permite transformar cada elemento y devolver un nuevo array?",
      options: [
        { label: "A", text: "forEach()" },
        { label: "B", text: "filter()" },
        { label: "C", text: "reduce()" },
        { label: "D", text: "map()" },
      ],
      correctAnswer: "D",
    },
    {
      id: "m3-q5",
      question: "¿Qué método del DOM se utiliza para seleccionar un elemento por su ID?",
      options: [
        { label: "A", text: "document.querySelector()" },
        { label: "B", text: "document.getElementById()" },
        { label: "C", text: "document.getElement()" },
        { label: "D", text: "document.findElement()" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m3-q6",
      question: "¿Qué devuelve el método filter() de un array?",
      options: [
        { label: "A", text: "El primer elemento que cumple la condición" },
        { label: "B", text: "Un valor booleano" },
        { label: "C", text: "Un nuevo array con todos los elementos que cumplen la condición" },
        { label: "D", text: "El índice de los elementos encontrados" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m3-q7",
      question: "¿Qué método se usa para agregar un evento a un elemento del DOM?",
      options: [
        { label: "A", text: "element.addEventListener()" },
        { label: "B", text: "element.addEvent()" },
        { label: "C", text: "element.on()" },
        { label: "D", text: "element.attachEvent()" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m3-q8",
      question: "¿Cuál es la diferencia entre let y var en JavaScript?",
      options: [
        { label: "A", text: "No hay diferencia, son equivalentes" },
        { label: "B", text: "let tiene ámbito de bloque, mientras que var tiene ámbito de función" },
        { label: "C", text: "var no permite reasignación" },
        { label: "D", text: "let es para constantes y var para variables" },
      ],
      correctAnswer: "B",
    },
  ],
  4: [
    {
      id: "m4-q1",
      question: "¿Qué método HTTP se utiliza para enviar datos al servidor con el fin de crear un nuevo recurso?",
      options: [
        { label: "A", text: "POST" },
        { label: "B", text: "GET" },
        { label: "C", text: "DELETE" },
        { label: "D", text: "OPTIONS" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m4-q2",
      question: "¿Qué API de JavaScript se utiliza para realizar peticiones HTTP asíncronas de forma moderna?",
      options: [
        { label: "A", text: "XMLHttpRequest" },
        { label: "B", text: "Fetch API" },
        { label: "C", text: "jQuery.ajax()" },
        { label: "D", text: "WebSocket" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m4-q3",
      question: "¿Cuál es la diferencia entre LocalStorage y SessionStorage?",
      options: [
        { label: "A", text: "No hay diferencia" },
        { label: "B", text: "LocalStorage persiste hasta que se elimina manualmente; SessionStorage se borra al cerrar la pestaña del navegador" },
        { label: "C", text: "SessionStorage tiene mayor capacidad" },
        { label: "D", text: "LocalStorage solo funciona en servidores" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m4-q4",
      question: "¿Qué método HTTP se utiliza para actualizar parcialmente un recurso existente?",
      options: [
        { label: "A", text: "PUT" },
        { label: "B", text: "POST" },
        { label: "C", text: "PATCH" },
        { label: "D", text: "GET" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m4-q5",
      question: "¿Qué código de estado HTTP indica que un recurso no fue encontrado?",
      options: [
        { label: "A", text: "200" },
        { label: "B", text: "301" },
        { label: "C", text: "500" },
        { label: "D", text: "404" },
      ],
      correctAnswer: "D",
    },
    {
      id: "m4-q6",
      question: "¿Qué Web API permite detectar cuándo un elemento entra o sale del viewport del navegador?",
      options: [
        { label: "A", text: "MutationObserver" },
        { label: "B", text: "ResizeObserver" },
        { label: "C", text: "IntersectionObserver" },
        { label: "D", text: "PerformanceObserver" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m4-q7",
      question: "¿Qué Web API permite obtener la ubicación geográfica del usuario?",
      options: [
        { label: "A", text: "Geolocation API" },
        { label: "B", text: "Navigation API" },
        { label: "C", text: "Position API" },
        { label: "D", text: "Map API" },
      ],
      correctAnswer: "A",
    },
  ],
  5: [
    {
      id: "m5-q1",
      question: "¿Qué comando de Git se utiliza para guardar los cambios preparados en el repositorio local?",
      options: [
        { label: "A", text: "git push" },
        { label: "B", text: "git commit" },
        { label: "C", text: "git add" },
        { label: "D", text: "git save" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m5-q2",
      question: "¿Qué es npm en el ecosistema de JavaScript?",
      options: [
        { label: "A", text: "Node Package Manager, el gestor de paquetes de Node.js" },
        { label: "B", text: "Un lenguaje de programación" },
        { label: "C", text: "Un framework de frontend" },
        { label: "D", text: "Un navegador web" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m5-q3",
      question: "¿Qué es un componente en React?",
      options: [
        { label: "A", text: "Una función de utilidad global" },
        { label: "B", text: "Una pieza reutilizable de interfaz que encapsula su propia lógica y presentación" },
        { label: "C", text: "Un archivo CSS independiente" },
        { label: "D", text: "Un módulo de Node.js" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m5-q4",
      question: "¿Cuál es la diferencia entre git pull y git fetch?",
      options: [
        { label: "A", text: "Son comandos equivalentes" },
        { label: "B", text: "git fetch descarga los cambios sin fusionarlos; git pull descarga y fusiona automáticamente" },
        { label: "C", text: "git pull solo funciona con repositorios remotos privados" },
        { label: "D", text: "git fetch sube cambios al remoto" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m5-q5",
      question: "¿Qué es un bundler en el ecosistema web moderno?",
      options: [
        { label: "A", text: "Un servidor web" },
        { label: "B", text: "Una herramienta que agrupa y optimiza módulos JavaScript, CSS y otros assets para producción" },
        { label: "C", text: "Un gestor de base de datos" },
        { label: "D", text: "Un framework de testing" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m5-q6",
      question: "¿Qué plataforma es comúnmente utilizada para desplegar sitios web estáticos de forma gratuita?",
      options: [
        { label: "A", text: "Microsoft Excel" },
        { label: "B", text: "Adobe Creative Cloud" },
        { label: "C", text: "Vercel o Netlify" },
        { label: "D", text: "Figma" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m5-q7",
      question: "¿Qué comando de Git se usa para crear una nueva rama y cambiar a ella simultáneamente?",
      options: [
        { label: "A", text: "git new branch" },
        { label: "B", text: "git branch --create nombre-rama" },
        { label: "C", text: "git checkout -b nombre-rama" },
        { label: "D", text: "git switch --new nombre-rama" },
      ],
      correctAnswer: "C",
    },
  ],
  6: [
    {
      id: "m6-q1",
      question: "¿Qué es un wireframe en el contexto del desarrollo web?",
      options: [
        { label: "A", text: "El código JavaScript final del proyecto" },
        { label: "B", text: "Un framework CSS" },
        { label: "C", text: "Un boceto visual de baja fidelidad que representa la estructura y disposición de una página web" },
        { label: "D", text: "Una herramienta de testing" },
      ],
      correctAnswer: "C",
    },
    {
      id: "m6-q2",
      question: "¿Por qué es importante usar etiquetas semánticas HTML en un portfolio profesional?",
      options: [
        { label: "A", text: "Mejoran la accesibilidad, el SEO y la legibilidad del código al dar significado a la estructura" },
        { label: "B", text: "Porque hacen que el código se vea más complejo" },
        { label: "C", text: "No tienen ningún impacto real" },
        { label: "D", text: "Solo son necesarias para sitios de comercio electrónico" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m6-q3",
      question: "¿Qué propiedad CSS se utiliza para crear animaciones fluidas de transición entre estados?",
      options: [
        { label: "A", text: "animation" },
        { label: "B", text: "transition" },
        { label: "C", text: "transform" },
        { label: "D", text: "movement" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m6-q4",
      question: "¿Cuál es la ventaja de usar CSS Grid para el layout de un portfolio?",
      options: [
        { label: "A", text: "Solo funciona para páginas simples" },
        { label: "B", text: "No es compatible con navegadores modernos" },
        { label: "C", text: "Requiere JavaScript para funcionar" },
        { label: "D", text: "Permite crear layouts bidimensionales complejos con filas y columnas de forma declarativa y responsiva" },
      ],
      correctAnswer: "D",
    },
    {
      id: "m6-q5",
      question: "¿Qué consideración es importante al desplegar un portfolio web?",
      options: [
        { label: "A", text: "Solo importa el diseño visual" },
        { label: "B", text: "Asegurar rendimiento, accesibilidad, SEO, certificado SSL y que funcione en dispositivos móviles" },
        { label: "C", text: "No es necesario optimizar imágenes" },
        { label: "D", text: "El dominio personalizado es obligatorio" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m6-q6",
      question: "¿Qué método de JavaScript se usa para agregar interactividad al hacer clic en un botón?",
      options: [
        { label: "A", text: "element.onClick()" },
        { label: "B", text: "element.addEventListener('click', callback)" },
        { label: "C", text: "element.clickHandler()" },
        { label: "D", text: "element.bindClick()" },
      ],
      correctAnswer: "B",
    },
    {
      id: "m6-q7",
      question: "¿Qué técnica de CSS permite crear animaciones con múltiples pasos y estados intermedios?",
      options: [
        { label: "A", text: "@keyframes con la propiedad animation" },
        { label: "B", text: "transition" },
        { label: "C", text: "hover" },
        { label: "D", text: "transform" },
      ],
      correctAnswer: "A",
    },
    {
      id: "m6-q8",
      question: "¿Cuál es la mejor práctica para la estructura de un proyecto web profesional?",
      options: [
        { label: "A", text: "Poner todo el código en un solo archivo" },
        { label: "B", text: "Usar solo JavaScript para todo" },
        { label: "C", text: "Separar la estructura (HTML), presentación (CSS) y comportamiento (JavaScript) en archivos organizados y mantenibles" },
        { label: "D", text: "No es necesario organizar los archivos" },
      ],
      correctAnswer: "C",
    },
  ],
};
